name: Build new Linux 6.6 LTS release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies and clone main repository
        run: |
          pacman -Syu --noconfirm base-devel git
          git clone --recursive https://github.com/${{ github.repository }} .

      - name: Export current and last built version
        run: |
          CURRENT_VERSION=$(grep '^pkgver=' linux-lts66/PKGBUILD | cut -d'=' -f2)

          if [[ -f last_built_version.txt ]]; then
            LAST_BUILT_VERSION=$(cat last_built_version.txt)
          else
            LAST_BUILT_VERSION=''
          fi

          echo "Current version: $CURRENT_VERSION"
          echo "Last built version: $LAST_BUILT_VERSION"

          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "LAST_BUILT_VERSION=$LAST_BUILT_VERSION" >> $GITHUB_ENV

      - name: Create dedicated user for building
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION }}
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder

      - name: Build the kernel
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION }}
        run: |
          cd linux-lts66

          sudo -u builder gpg --locate-keys torvalds@kernel.org
          sudo -u builder gpg --locate-keys gregkh@kernel.org

          chown -R builder .
          sudo -u builder MAKEFLAGS="-j$(nproc)" makepkg -s --noconfirm

      - name: Upload compiled packages
        if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-lts66-${{ env.CURRENT_VERSION }}
          path: linux-lts66/*.pkg.tar.zst

      - name: Update last built version
        #if: ${{ env.CURRENT_VERSION != env.LAST_BUILT_VERSION }}
        run: |
          echo $CURRENT_VERSION > last_built_version.txt

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add last_built_version.txt
          git commit -m "Update last built version to $CURRENT_VERSION"
          git push