name: Build new Linux 6.6 LTS release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies and clone repositories
        run: |
          pacman -Syu --noconfirm base-devel git
          git clone https://aur.archlinux.org/linux-lts66.git
          git clone https://github.com/${{ github.repository }}.git

      - name: Extract package version and check if version build exists
        run: |
          CURRENT_VERSION=$(grep '^pkgver=' linux-lts66/PKGBUILD | cut -d'=' -f2)

          if [[ -f linux-lts66-builder/last_built_version.txt ]]; then
            LAST_BUILT_VERSION=$(cat linux-lts66-builder/last_built_version.txt)
          fi

          echo $CURRENT_VERSION
          echo $LAST_BUILT_VERSION

          if [[ "$CURRENT_VERSION" == "$LAST_BUILT_VERSION" ]]; then
            exit 0
          fi

          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Create dedicated user for building
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder

      - name: Build the kernel
        run: |
          cd linux-lts66

          sudo -u builder gpg --locate-keys torvalds@kernel.org
          sudo -u builder gpg --locate-keys gregkh@kernel.org

          chown -R builder .
          sudo -u builder MAKEFLAGS="-j$(nproc)" makepkg -s --noconfirm

      - name: Upload compiled packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-lts66-${{ env.CURRENT_VERSION }}
          path: linux-lts66/*.pkg.tar.zst

      - name: Update last built version
        run: |
          cd linux-lts66-builder
          echo "$CURRENT_VERSION" > last_built_version.txt

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add last_built_version.txt
          git commit -m "Update last built version to $CURRENT_VERSION"
          git push