name: Build new Linux 6.6 LTS release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and clone AUR package base
        run: |
          pacman -Syu --noconfirm base-devel git
          git clone https://aur.archlinux.org/linux-lts66.git

      - name: Extract package version
        run: |
          cd linux-lts66
          echo "VERSION=$(grep '^pkgver=' PKGBUILD | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Check if version build exists
        run: |
          if [[ -f last_built_version.txt ]]; then
            LAST_BUILT_VERSION=$(cat last_built_version.txt)
          fi

          if [[ "$VERSION" == "$LAST_BUILT_VERSION" ]]; then
            exit 0
          fi

      - name: Create dedicated user for package build
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder

      - name: Build the kernel
        run: |
          cd linux-lts66

          sudo -u builder gpg --locate-keys torvalds@kernel.org
          sudo -u builder gpg --locate-keys gregkh@kernel.org

          sudo chown -R builder .
          sudo -u builder makepkg -s --noconfirm

      - name: Upload compiled packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-lts66-${{ env.VERSION }}
          path: linux-lts66/*.pkg.tar.zst

      - name: Update last built version
        run: |
          echo "$VERSION" > last_built_version.txt

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add last_built_version.txt
          git commit -m "Update last built version to $VERSION"
          git push

